<?php include("barre.php");
echo htmlspecialchars($_SESSION['login']);
include("config.php");
$sql="SELECT id FROM login WHERE pseudo= '".$_SESSION['login']."'";
$rep = $conn->query($sql);
$result=$rep->fetch_assoc();
$sql="DELETE FROM fav_style WHERE id_style='".$_GET['id_style']."'AND id_login='".$result['id']."' ";
//echo "$sql";
$rep = $conn->query($sql);
$dest="style_fav.php";
 echo '<script language="JavaScript">window.location=\'' . $dest . '\'</script>';
exit;
